name: 2. Node.js CD

on: 
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  deploy-on-push:
    name: deploy-on-push
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd ~/Phodo-server
            git pull origin main
            pm2 kill
            npm i --force
            pm2 start server.js

  deploy-on-pr-merged:
    name: deploy-on-pr-merged
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd ~/Phodo-server
            git pull origin main
            pm2 kill
            npm i --force
            pm2 start server.js
